import numpy as np
from models import Song
from business_rules import run_all

song_list = {"I Can't Get No (Satisfaction)" : Song(
                ['sharp', 'hard', 'simple', 'repetitive', 'upbeat', 'steady'],
                ['vocals', 'lead guitar', 'rhythm guitar', 'drums', 'bass guitar'],
                5,
                ['angry'],
                ['angry', 'energetic', 'determined'],
                'rock'),
            "Good Times Bad Times" : Song(
                ['hard', 'hurried', 'distorted'],
                ['vocals', 'lead guitar', 'bass guitar', 'drums'],
                4,
                ['determined', 'energetic'],
                ['determined', 'energetic'],
                'rock'),
            "All Along the Watch Tower" : Song(
                ['rough', 'melodic', 'steady'],
                ['vocals', 'lead guitar', 'bass guitar', 'drums'],
                4,
                ['angry', 'determined', 'tense', 'depressed'],
                ['angry', 'determined', 'tense'],
                'rock'),
            "Monkey Wrench" : Song(
                ['rough', 'hurried', 'grungy', 'distorted'],
                ['vocals', 'lead guitar', 'bass guitar', 'drums'],
                4,
                ['angry', 'depressed'],
                ['angry', 'energetic'],
                'rock'),
            "Locomotive Breath" : Song(
                ['hard', 'steady', 'sharp'],
                ['vocals', 'piano', 'drums', 'bass guitar', 'lead guitar', 'rhythm guitar'],
                7,
                ['determined', 'depressed', 'hurt'],
                ['determined', 'tense'],
                'rock'),
            "Lucille" : Song(
                ['sharp', 'steady', 'homey'],
                ['vocals', 'lead guitar', 'piano', 'bass guitar', 'saxophone', 'drums'],
                5,
                ['determined', 'depressed', 'lost'],
                ['determined', 'tense', 'lost'],
                'blues'),
            "Hoochie Coochie Man" : Song(
                ['smooth', 'steady'],
                ['vocals', 'bass guitar', 'drums', 'lead guitar'],
                5,
                ['depressed', 'hurt'],
                ['depressed', 'hurt'],
                'blues'),
            "Texas Flood" : Song(
                ['sharp', 'steady', 'twangy', 'rough', 'distorted', 'hard'],
                ['vocals', 'lead guitar', 'bass guitar', 'drums'],
                4,
                ['depressed', 'proud'],
                ['depressed', 'determined'],
                'blues'),
            "Born Under A Bad Sign" : Song(
                ['steady', 'smooth', 'homey', 'grounded'],
                ['vocals', 'piano', 'bass guitar', 'drums', 'lead guitar', 'rhythm guitar', 'horns'],
                8,
                ['depressed', 'hurt'],
                ['depressed', 'hurt'],
                'blues'),
            "Statesboro Blues" : Song(
                ['smooth', 'hard'],
                ['vocals', 'lead guitar', 'rhythm guitar', 'bass guitar', 'drums'],
                4,
                ['depressed', 'hurt', 'lost'],
                ['depressed', 'anxious', 'determined'],
                'blues'),
            "Straight Outta Compton" : Song(
                ['edgy', 'rough', 'hard'],
                ['vocals', 'drums', 'horns', 'rhythm guitar'],
                4,
                ['angry', 'energetic'],
                ['angry', 'tense', 'energetic'],
                'rap'),
            "Gold Digger" : Song(
                ['steady', 'bassheavy', 'hard'],
                ['vocals', 'drums', 'horns'],
                2,
                ['angry', 'determined'],
                ['angry', 'determined'],
                'rap'),
            "Rap God" : Song(
                ['complex', 'hurried', 'upbeat', 'hard', 'chaotic'],
                ['vocals', 'drums', 'piano', 'synthesizer'],
                1,
                ['proud', 'determined'],
                ['angry', 'determined', 'tense', 'energetic'],
                'rap'),
            "HUMBLE." : Song(
                ['hard', 'repetitive', 'steady'],
                ['vocals', 'drums', 'piano', 'synthesizer'],
                1,
                ['proud', 'determined'],
                ['proud', 'determined'],
                'rap'),
            "Hotline Bling" : Song(
                ['smooth', 'repetitive', 'hard'],
                ['vocals', 'drums', 'synthesizer'],
                1,
                ['hurt', 'depressed', 'lost'],
                ['hurt', 'determined'],
                'rap'),
            "Firework" : Song(
                ['upbeat', 'peppy', 'melodic'],
                ['vocals', 'drums', 'synthesizer', 'bass guitar', 'violin'],
                1,
                ['amazed', 'energetic', 'happy'],
                ['amazed', 'energetic', 'happy'],
                'pop'),
            "Toxic" : Song(
                ['upbeat', 'edgy'],
                ['vocals', 'drums', 'bass guitar', 'rhythm guitar', 'violin'],
                1,
                ['energetic', 'determined'],
                ['anxious', 'energetic'],
                'pop'),
            "Billie Jean" : Song(
                ['smooth', 'repetitive', 'round'],
                ['vocals', 'drums', 'bass guitar', 'rhythm guitar', 'synthesizer', 'violin'],
                1,
                ['determined', 'energetic'],
                ['energetic', 'tense'],
                'pop'),
            "Take On Me" : Song(
                ['upbeat', 'peppy', 'melodic'],
                ['vocals', 'drums', 'synthesizer', 'bass guitar', 'piano'],
                3,
                ['happy', 'energetic', 'loving'],
                ['happy', 'energetic'],
                'pop'),
            "Marry You" : Song(
                ['simple', 'peppy', 'melodic', 'upbeat', 'repetitive'],
                ['vocals', 'drums', 'piano', 'rhythm guitar'],
                4,
                ['loving', 'happy', 'content'],
                ['happy', 'content', 'energetic'],
                'pop'),
            "Wagon Wheel" : Song(
                ['leisurly', 'soft', 'homey', 'acoustical'],
                ['vocals', 'violin', 'rhythm guitar', 'bass guitar'],
                6,
                ['loving', 'content', 'proud'],
                ['loving', 'content', 'proud'],
                'country'),
            "Amazed" : Song(
                ['soft', 'twangy', 'melodic', 'homey', 'smooth'],
                ['vocals', 'piano', 'drums', 'rhythm guitar', 'violin', 'bass guitar'],
                6,
                ['amazed', 'inspired', 'proud'],
                ['amazed', 'inspired', 'proud'],
                'country'),
            "Wide Open Spaces" : Song(
                ['smooth', 'homey', 'melodic', 'leisurly'],
                ['vocals', 'rhythm guitar', 'lead guitar', 'bass guitar', 'drums', 'violin'],
                5,
                ['proud', 'content'],
                ['proud', 'content'],
                'country'),
            "Jesus, Take the Wheel" : Song(
                ['patriotic', ''],
                ['vocals', 'violin', 'piano', 'drums', 'bass guitar', 'lead guitar'],
                6,
                ['amazed', 'inspired', 'proud'],
                ['inspired', 'proud'],
                'country'),
            "I Walk the Line" : Song(
                ['smooth', 'acoustical', 'homey'],
                ['vocals', 'lead guitar', 'rhythm guitar', 'drums'],
                3,
                ['proud', 'content'],
                ['proud', 'content'],
                'country'),
            "Three Little Birds" : Song(
                ['smooth', 'leisurly', 'slow'],
                ['vocals', 'drums', 'rhythm guitar', 'piano', 'bass guitar'],
                8,
                ['content', 'loving', 'peaceful'],
                ['content', 'loving', 'peaceful'],
                'reggae'),
            "Bombastic" : Song(
                ['leisurly', 'slow', 'repetitive', 'grounded'],
                ['vocals', 'drums', 'piano', 'synthesizer', 'bass guitar'],
                3,
                ['content', 'determined'],
                ['content', 'annoyed'],
                'reggae'),
            "Welcome to Jamrock" : Song(
                ['leisurly', 'steady', 'grounded'],
                ['vocals', 'drums', 'bass guitar', 'rhythm guitar'],
                5,
                ['content', 'peaceful', 'determined'],
                ['content', 'determined'],
                'reggae'),
            "Red Red Wine" : Song(
                ['leisurly', 'slow', 'smooth'],
                ['vocals', 'drums', 'bass guitar', 'rhythm guitar'],
                5,
                ['content', 'loving', 'peaceful'],
                ['content', 'loving', 'peaceful'],
                'reggae'),
            "Amber" : Song(
                ['leisurly', 'smooth', 'melodic', 'steady'],
                ['vocals', 'drums', 'bass guitar', 'rhythm guitar', 'lead guitar'],
                5,
                ['peaceful', 'content'],
                ['peaceful', 'content'],
                'reggae'),
            "Levels" : Song(
                ['upbeat', 'peppy', 'bassheavy'],
                ['vocals', 'drums', 'synthesizer'],
                1,
                ['amazed', 'inspired', 'energetic', 'happy'],
                ['energetic', 'amazed', 'happy'],
                'electronic'),
            "Harder Better Faster Stronger" : Song(
                ['upbeat', 'repetitive', 'peppy', 'steady'],
                ['vocals', 'synthesizer', 'drums'],
                2,
                ['determined', 'energetic'],
                ['determined', 'energetic'],
                'electronic'),
            "Strobe" : Song(
                ['upbeat', 'repetitive', 'steady'],
                ['drums', 'synthesizer'],
                1,
                ['determined', 'energetic'],
                ['determined', 'energetic'],
                'electronic'),
            "Scary Monsters And Nice Sprites" : Song(
                ['upbeat', 'hard', 'repetitive', 'bassheavy', 'chaotic'],
                ['vocals', 'drums', 'synthesizer'],
                1,
                ['determined', 'energetic'],
                ['determined', 'energetic', 'tense'],
                'electronic'),
            "Xenogenesis" : Song(
                ['chaotic', 'hard', 'steady', 'bassheavy'],
                ['drums', 'synthesizer'],
                1,
                ['determined', 'energetic', 'proud'],
                ['determined', 'energetic', 'proud'],
                'electronic'),
            "Flight of the Valkyries" : Song(
                ['complex', 'steady', 'melodic', 'edgy', 'chaotic'],
                ['piano', 'horns', 'violin', 'drums'],
                60,
                ['proud', 'amazed', 'inspired', 'determined'],
                ['inspired', 'determined', 'proud'],
                'classical'),
            "Symphony No. 5" : Song(
                ['complex', 'melodic', 'hurried', 'sharp'],
                ['piano', 'horns', 'violin', 'drums'],
                60,
                ['anxious', 'tense', 'determined'],
                ['anxious', 'tense', 'determined'],
                'classical'),
            "Fanfare For The Common Man" : Song(
                ['patriotic', 'melodic', 'steady', 'grounded'],
                ['piano', 'horns', 'violin', 'drums'],
                60,
                ['proud', 'amazed', 'inspired'],
                ['proud', 'amazed', 'inspired'],
                'classical'),
            "The Four Seasons - Spring" : Song(
                ['soft', 'leisurly', 'complex', 'melodic', 'peppy'],
                ['violin', 'piano'],
                20,
                ['happy', 'peaceful', 'energetic'],
                ['happy', 'peaceful'],
                'classical'),
            "Nocturne Op. 9 No. 2" : Song(
                ['steady', 'complex', 'slow', 'smooth'],
                ['piano'],
                1,
                ['peaceful', 'content'],
                ['peaceful', 'content'],
                'classical'),
            "Cecilia" : Song(
                ['homey', 'simple', 'acoustical', 'grounded'],
                ['vocals', 'rhythm guitar', 'drums'],
                3,
                ['loving', 'happy'],
                ['loving', 'happy'],
                'folk'),
            "This Land Is Your Land" : Song(
                ['patriotic', 'acoustical', 'homey', 'round'],
                ['vocals', 'rhythm guitar'],
                1,
                ['proud', 'content', 'peaceful'],
                ['proud', 'content', 'peaceful'],
                'folk'),
            "If I Had A Hammer" : Song(
                ['patriotic', 'acoustical', 'homey', 'round'. 'peppy'],
                ['vocals', 'rhythm guitar'],
                3,
                ['loving', 'happy', 'proud'],
                ['loving', 'happy'],
                'folk'),
            "Blue Moon of Kentucky" : Song(
                ['patriotic', 'acoustical', 'homey', 'steady', 'melodic'],
                ['vocals', 'rhythm guitar', 'violin'],
                3,
                ['proud', 'peaceful', 'content'],
                ['proud', 'peaceful', 'content'],
                'folk'),
            "The Last Thing On My Mind" : Song(
                ['soft', 'homey', 'grounded', 'smooth'],
                ['vocals', 'rhythm guitar'],
                1,
                ['proud', 'peaceful', 'content'],
                ['peaceful', 'content'],
                'folk'),
            "The Girl From Ipanema" : Song(
                ['smooth', 'acoustical', 'melodic', 'simple', 'soft'],
                ['vocals', 'rhythm guitar', 'bass guitar', 'drums', 'saxophone', 'piano'],
                6,
                ['loving', 'hurt', 'lost', 'peaceful'],
                ['loving', 'hurt', 'peaceful'],
                'world'),
            "El Cuarto De Tula" : Song(
                ['proud', 'steady', 'homey', 'acoustical'],
                ['vocals', 'drums', 'horns', 'bass guitar', 'rhythm guitar'],
                8,
                ['determined', 'energetic'],
                ['happy', 'energetic'],
                'world'),
            "El Besu" : Song(
                ['patriotic', 'steady', 'grounded'],
                ['vocals', 'drums'],
                6,
                ['proud', 'inspired', 'happy'],
                ['proud', 'inspired', 'happy'],
                'world'),
            "Rain, Rain, Beautiful Rain" : Song(
                ['smooth', 'soft', 'homey'],
                ['vocals'],
                10,
                ['amazed', 'content', 'peaceful'],
                ['amazed', 'peaceful', 'content'],
                'world'),
            "Dhun" : Song(
                ['sharp', 'homey', 'chaotic'],
                ['drums'],
                3,
                ['peaceful', 'content'],
                ['peaceful', 'content'],
                'world')}

if __name__ == '__main__':
    genre_list = {}
    incorrect_list = []
    for song in song_list:
        genre_list[song] = song.genre
        run_all(rule_list=self.rules, #FIX where rules list comes from
            defined_variables=SongVariables(song_list[song]),
            defined_actions=SongActions(song_list[song]),
            stop_on_first_trigger=False
            )
        if song.genre != genre_list[song]:
            incorrect_list.append(song)
    print(incorrect_list)
    print("Number incorrect: %n") % (length(incorrect_list), )